# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rocket}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Araneo", "Kriss Kowalik"]
  s.date = %q{2010-11-01}
  s.default_executable = %q{rocket}
  s.description = %q{      Rocket is a very fast and reliable websocket server built upon em-websockets library.
      Rocket provides also javascript toolkit to serve up instructions to clients. 
      All Rocket's behaviors was strongly inspired by awesome PusherApp. 
}
  s.email = %q{chris@nu7hat.ch}
  s.executables = ["rocket"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".gitignore",
     "README.md",
     "Rakefile",
     "bin/rocket",
     "lib/rocket.rb",
     "lib/rocket/app.rb",
     "lib/rocket/channel.rb",
     "lib/rocket/cli.rb",
     "lib/rocket/connection.rb",
     "lib/rocket/helpers.rb",
     "lib/rocket/misc.rb",
     "lib/rocket/server.rb",
     "lib/rocket/session.rb",
     "lib/rocket/templates/config.yml.tpl",
     "lib/rocket/version.rb",
     "spec/apps_spec.rb",
     "spec/channel_spec.rb",
     "spec/cli_spec.rb",
     "spec/connection_spec.rb",
     "spec/helpers_spec.rb",
     "spec/misc_spec.rb",
     "spec/rocket_spec.rb",
     "spec/server_spec.rb",
     "spec/session_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{https://github.com/araneo/rocket}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Fast and extensible websocket server for Ruby.}
  s.test_files = [
    "spec/helpers_spec.rb",
     "spec/server_spec.rb",
     "spec/connection_spec.rb",
     "spec/misc_spec.rb",
     "spec/spec_helper.rb",
     "spec/apps_spec.rb",
     "spec/cli_spec.rb",
     "spec/channel_spec.rb",
     "spec/session_spec.rb",
     "spec/rocket_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<optitron>, ["~> 0.2"])
      s.add_runtime_dependency(%q<json>, ["~> 1.4"])
      s.add_runtime_dependency(%q<eventmachine>, [">= 0.12"])
      s.add_runtime_dependency(%q<em-websocket>, [">= 0.1.4"])
      s.add_runtime_dependency(%q<logging>, ["~> 1.4"])
      s.add_runtime_dependency(%q<daemons>, ["~> 1.1"])
      s.add_runtime_dependency(%q<konfigurator>, [">= 0.1.1"])
      s.add_development_dependency(%q<rspec>, ["~> 2.0"])
      s.add_development_dependency(%q<mocha>, ["~> 0.9"])
    else
      s.add_dependency(%q<optitron>, ["~> 0.2"])
      s.add_dependency(%q<json>, ["~> 1.4"])
      s.add_dependency(%q<eventmachine>, [">= 0.12"])
      s.add_dependency(%q<em-websocket>, [">= 0.1.4"])
      s.add_dependency(%q<logging>, ["~> 1.4"])
      s.add_dependency(%q<daemons>, ["~> 1.1"])
      s.add_dependency(%q<konfigurator>, [">= 0.1.1"])
      s.add_dependency(%q<rspec>, ["~> 2.0"])
      s.add_dependency(%q<mocha>, ["~> 0.9"])
    end
  else
    s.add_dependency(%q<optitron>, ["~> 0.2"])
    s.add_dependency(%q<json>, ["~> 1.4"])
    s.add_dependency(%q<eventmachine>, [">= 0.12"])
    s.add_dependency(%q<em-websocket>, [">= 0.1.4"])
    s.add_dependency(%q<logging>, ["~> 1.4"])
    s.add_dependency(%q<daemons>, ["~> 1.1"])
    s.add_dependency(%q<konfigurator>, [">= 0.1.1"])
    s.add_dependency(%q<rspec>, ["~> 2.0"])
    s.add_dependency(%q<mocha>, ["~> 0.9"])
  end
end

