# -*- ruby -*-

$:.unshift(File.expand_path('../lib', __FILE__))
$:.unshift(File.expand_path('../../rocket/lib', __FILE__))

require 'rspec/core/rake_task'
require 'rake/rdoctask'
require 'rocket/server/version'

SUMMARY = %Q{Fast and extensible web socket server built upon em-websockets.}
DESCRIPTION = %Q{
This is a fast web socket server built on awesome EventMachine with em-websockets help. 
It provides easy to use, event-oriented middleware for your web-socket powered applications.    
}

begin
  require 'jeweler'
  Jeweler::Tasks.new do |gem|
    gem.version = Rocket::Server.version
    gem.name = "rocket-server"
    gem.email = "chris@nu7hat.ch"
    gem.homepage = "http://github.com/araneo/rocket"
    gem.authors = ["Araneo", "Chris Kowalik"]
    gem.summary = SUMMARY
    gem.description = DESCRIPTION
    #gem.add_dependency "rocket", "0.0.1"
    gem.add_dependency "optitron", "~> 0.2"
    gem.add_dependency "json", "~> 1.4"
    gem.add_dependency "eventmachine", ">= 0.12"
    gem.add_dependency "em-websocket", ">= 0.1.4"
    gem.add_dependency "logging", "~> 1.4"
    gem.add_dependency "daemons", "~> 1.1"
    gem.add_dependency "konfigurator", ">= 0.1.1"
    gem.add_development_dependency "rspec", "~> 2.0"
    gem.add_development_dependency "mocha", "~> 0.9"
  end
  Jeweler::GemcutterTasks.new
rescue
  puts 'Jeweler is not available here'
end

RSpec::Core::RakeTask.new(:spec) do |t|
  t.pattern = 'spec/**/*_spec.rb'
  t.rspec_opts = %q[-I../rocket/lib -Ilib -c -b]
end

RSpec::Core::RakeTask.new(:rcov) do |t|
  t.rcov = true
  t.rspec_opts = %q[-I../rocket/lib -Ilib -c -b]
  t.rcov_opts = %q[-I../rocket/lib -Ilib -T -x "spec"]
end

Rake::RDocTask.new do |rdoc|
  rdoc.title = "Rocket server #{Rocket::Server.version}"
  rdoc.rdoc_dir = 'rdoc'
  rdoc.rdoc_files.include('README*')
  rdoc.rdoc_files.include('lib/**/*.rb')
end

task :default => :spec
