# -*- ruby -*-
$:.unshift(File.expand_path('../lib', __FILE__))
require 'rspec/core/rake_task'
require 'rake/rdoctask'
require 'rocket/version'

RSpec::Core::RakeTask.new(:spec) do |t|
  t.pattern = 'spec/**/*_spec.rb'
  t.rspec_opts = %q[-I../rocket/lib -Ilib -c -b]
end

RSpec::Core::RakeTask.new(:rcov) do |t|
  t.rcov = true
  t.rspec_opts = %q[-I../rocket/lib -Ilib -c -b]
  t.rcov_opts = %q[-I../rocket/lib -Ilib -T -x "spec"]
end

Rake::RDocTask.new do |rdoc|
  rdoc.title = "Rocket #{Rocket.version}"
  rdoc.rdoc_dir = 'rdoc'
  rdoc.rdoc_files.include('README*')
  rdoc.rdoc_files.include('lib/**/*.rb')
end

desc "Build current version as a rubygem"
task :build do
  `gem build rocket-server.gemspec`
  `mkdir -p pkg`
  `mv rocket-server-*.gem pkg/`
end

desc "Relase current version to rubygems.org"
task :release => :build do
  `gem push pkg/rocket-server-#{Rocket.version}.gem`
end

desc "Perform installation via rubygems"
task :install => :build do
  `gem install pkg/rocket-server-#{Rocket.version}.gem`
end

task :default => :spec
