# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rocket}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Araneo", "Chris Kowalik"]
  s.date = %q{2010-11-03}
  s.description = %q{
Rocket is a very fast and reliable web socket server built upon em-websockets library.
Rocket provides also JavaScript toolkit to serve up instructions to clients, and
ruby library which handles events triggering. This Project was strongly inspired 
by awesome PusherApp.
}
  s.email = %q{chris@nu7hat.ch}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.md",
     "Rakefile",
     "bin/rocket",
     "lib/rocket.rb",
     "lib/rocket/channel.rb",
     "lib/rocket/client.rb",
     "lib/rocket/helpers.rb",
     "lib/rocket/version.rb",
     "lib/rocket/websocket.rb",
     "rocket.gemspec",
     "spec/helpers_spec.rb",
     "spec/rocket_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/araneo/rocket}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Event-oriented WebSockets server and toolkit.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rocket-server>, ["= 0.0.1"])
      s.add_runtime_dependency(%q<rocket-js>, ["= 0.0.1"])
      s.add_runtime_dependency(%q<json>, ["~> 1.4"])
      s.add_development_dependency(%q<rspec>, ["~> 2.0"])
      s.add_development_dependency(%q<mocha>, ["~> 0.9"])
    else
      s.add_dependency(%q<rocket-server>, ["= 0.0.1"])
      s.add_dependency(%q<rocket-js>, ["= 0.0.1"])
      s.add_dependency(%q<json>, ["~> 1.4"])
      s.add_dependency(%q<rspec>, ["~> 2.0"])
      s.add_dependency(%q<mocha>, ["~> 0.9"])
    end
  else
    s.add_dependency(%q<rocket-server>, ["= 0.0.1"])
    s.add_dependency(%q<rocket-js>, ["= 0.0.1"])
    s.add_dependency(%q<json>, ["~> 1.4"])
    s.add_dependency(%q<rspec>, ["~> 2.0"])
    s.add_dependency(%q<mocha>, ["~> 0.9"])
  end
end

