desc 'Bundle and minify source files.'
task :build do
  require File.expand_path('../lib/builder', __FILE__)
  Builder.build
end

desc 'Start test server.'
task :test do
  exec 'ruby -I../rocket/lib test/app.rb'
end

task :default => :test
