# -*- ruby -*-

$:.unshift(File.expand_path('../lib', __FILE__))
$:.unshift(File.expand_path('../../rocket/lib/', __FILE__))

require 'rspec/core/rake_task'
require 'rake/rdoctask'
require 'rocket/js/version'

SUMMARY = %Q{JavaScript client library for Rocket server.}
DESCRIPTION = %Q{
This library is client that allows JavaScript clients to connect to the 
Rocket web socket server.
}

begin
  require 'jeweler'
  Jeweler::Tasks.new do |g|
    g.version = Rocket::JS.version
    g.name = "rocket-js"
    g.email = "chris@nu7hat.ch"
    g.homepage = "http://github.com/araneo/rocket"
    g.authors = ["Araneo", "Chris Kowalik"]
    g.summary = SUMMARY
    g.description = DESCRIPTION
    g.executables = %w[rocket-js]
    g.files += Dir[File.join(File.dirname(__FILE__) + "../src/**/*")]
    g.files += Dir[File.join(File.dirname(__FILE__) + "../src/vendor/web-socket-js/**/*")]
    #g.add_dependency "rocket", "0.0.1"
    g.add_dependency "json", "~> 1.4"
    g.add_dependency "yui-compressor", "~> 0.9"
    g.add_development_dependency "rspec", "~> 2.0"
    g.add_development_dependency "mocha", "~> 0.9"
    g.add_development_dependency "jasmine", "~> 1.0"
  end
  Jeweler::GemcutterTasks.new
rescue
  puts 'Jeweler is not available here'
end

namespace :js do
  desc 'Bundle and minify source files.'
  task :build do
    require 'rocket-js'
    require 'rocket/js/builder'
    Rocket::JS::Builder.new(File.dirname(__FILE__), true).generate_script
  end

  desc 'Start test server.'
  task :test do
    exec 'ruby -I../rocket/lib -Ilib test/js/app.rb'
  end
end

RSpec::Core::RakeTask.new(:spec) do |t|
  t.pattern = 'spec/ruby/**/*_spec.rb'
  t.rspec_opts = %q[-Ilib -c -b]
end

RSpec::Core::RakeTask.new(:rcov) do |t|
  t.rcov = true
  t.rspec_opts = %q[-Ilib -c -b]
  t.rcov_opts = %q[-Ilib -T -x "spec"]
end

Rake::RDocTask.new do |rdoc|
  rdoc.title = "Rocket JavaScript Tools #{Rocket::JS.version}"
  rdoc.rdoc_dir = 'rdoc'
  rdoc.rdoc_files.include('README*')
  rdoc.rdoc_files.include('lib/**/*.rb')
end

task :default => :spec
