# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rocket-js}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Araneo", "Chris Kowalik"]
  s.date = %q{2010-11-04}
  s.default_executable = %q{rocket-js}
  s.description = %q{
This library is client that allows JavaScript clients to connect to the 
Rocket web socket server.
}
  s.email = %q{chris@nu7hat.ch}
  s.executables = ["rocket-js"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = Dir[File.join(File.dirname(__FILE__), "**/*")].to_a
  s.homepage = %q{http://github.com/araneo/rocket}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{JavaScript client library for Rocket server.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<json>, ["~> 1.4"])
      s.add_runtime_dependency(%q<yui-compressor>, ["~> 0.9"])
      s.add_development_dependency(%q<rspec>, ["~> 2.0"])
      s.add_development_dependency(%q<mocha>, ["~> 0.9"])
      s.add_development_dependency(%q<jasmine>, ["~> 1.0"])
    else
      s.add_dependency(%q<json>, ["~> 1.4"])
      s.add_dependency(%q<yui-compressor>, ["~> 0.9"])
      s.add_dependency(%q<rspec>, ["~> 2.0"])
      s.add_dependency(%q<mocha>, ["~> 0.9"])
      s.add_dependency(%q<jasmine>, ["~> 1.0"])
    end
  else
    s.add_dependency(%q<json>, ["~> 1.4"])
    s.add_dependency(%q<yui-compressor>, ["~> 0.9"])
    s.add_dependency(%q<rspec>, ["~> 2.0"])
    s.add_dependency(%q<mocha>, ["~> 0.9"])
    s.add_dependency(%q<jasmine>, ["~> 1.0"])
  end
end

